# Configuration statique Traefik pour le reverse proxy/"serveur fant√¥me"
api:
  dashboard: true
log:
  level: INFO
accessLog: {}
certificatesResolvers:
  dev:
    acme:
      email: ops@traceguard.local
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
